/**
 * @Name: ScheduleFitbitSync
 * @Created: March 2019
 * @Author: Jason Auger
 * @Description: Used to create scheduled job for Fitbit Synchronisation
 */
public with sharing class ScheduleFitbitSync {
    public ScheduleFitbitSync() {

    }

    /**
     * @name: scheule
     * @created: March 2019
     * @author: Jason Auger
     * @desciption: Scheules the Fitbit sync job.  Static method.
     */
    public static void schedule() {
        //  Check to see if scheduled job already exists

        //  Delete existing scheduled job if exists

        //  Create fresh scheduled job

    }
}