/**
 * @class:
 * @test:
 * @author
 * @desc: NOT A TESTING UNIT TEST CLASS.  Uses SObjectUtil to create SObjectUtil instances for unit tests
 */
public class TestSObjectUtilFactory {

    public class TestSObjectUtilFactoryException extends Exception {}

    // private static Map<String, SObjectUtil> mapSObjectUtils = new Map<String, SObjectUtil>();

    // public static SObjectUtil getSObjectUtil(String objectName) {
    //     if (mapSObjectUtils.containsKey(objectName) == false) {
    //         mapSObjectUtils.put(objectName, new SObjectUtil(objectName));
    //     }
    //     return mapSObjectUtils.get(objectName);
    // }


    // SObjectUtil.get('Account').getDefaultRecordId();

    // TestSObjectUtilFactory.get('Account').getDefaultRecordId();
    // TestSObjectUtilFactory.get('Contact').getDefaultRecordId();
}