/**
 * Class: TestScheduleFitbitSync.cls
 * Test class for: ScheduleFitbitSync.cls
 */ 
@isTest
public class TestScheduleFitbitSync {

    /**
     * Remove all existing scheduled tasks/jobs
     */
    @TestSetup
    static void makeData(){
      
    }

    /**
     * Test to see if the scheduled job is being created successfully
     * and is set to being run at the correct time.
     */
    @isTest
    static void testScheduling(){

    }
}